# Generated by Django 3.0.3 on 2020-02-07 02:42
# Generated by Django 3.0.3 on 2020-02-07 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200206_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
